string(APPEND CONFIG_ARGS " --host=cray")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_SLASHPROC -DHAVE_GETTIMEOFDAY")
endif()
string(APPEND CMAKE_C_FLAGS_RELEASE " -O2 -g")
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -O2 -g")
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")

# FKB (Sungduk Yu, Thu 21 Sep 2023 05:12:11 PM PDT)
string(APPEND CMAKE_Fortran_FLAGS " -I/global/cfs/cdirs/m4331/shared/FKB64/build/include ")
string(APPEND CMAKE_EXE_LINKER_FLAGS " -L/global/cfs/cdirs/m4331/shared/FKB64/build/lib -lneural ")